# Generated by Django 5.0 on 2024-01-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0002_subscribe_option_alter_subscribe_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="option",
            field=models.CharField(
                choices=[("W", "Weekly"), ("M", "Monthly")], max_length=2
            ),
        ),
    ]
