# Generated by Django 5.0 on 2023-12-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_jobpost_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="expiry",
            field=models.DateTimeField(null=True),
        ),
    ]
