# Generated by Django 5.0 on 2024-01-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploadapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_description", models.CharField(max_length=100)),
            ],
        ),
    ]
